[package]
name = "hello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
foo = {path = "../foo"}
log2 = {path = "../log2"}
log = "0.4"
log4rs = "1.3.0"
